spring:
  application:
    name: usuarios
server:
  port: 8096
google:
  firebase:
    credentials: C:\\Users\\User\\Documents\\maestriacomputacion\\Despliegue\\prod-maestria-computacion-firebase-adminsdk-6hpr7-4199a1844b.json
kira:
  api:
    url: http://10.200.1.181:8081/api/v1

app:
  jwtSecret: claveSuperSecretaMaestriaComputacionKeySecretMCouieeaASdwwwieryyCBD14251ssass11234DDAccsrtrt22
  jwtExpirationMs: 86400000
