spring:
  application:
    name: usuarios
server:
  port: 8096
google:
  firebase:
    credentials: C:\\Users\\User\\Documents\\maestriacomputacion\\Despliegue\\prod-maestria-computacion-firebase-adminsdk-6hpr7-4199a1844b.json
kira:
  api-url: "https://api.kira.edu/usuarios"
