spring:
  application:
    name: usuarios
server:
  port: ${SERVER_PORT}
google:
  firebase:
    credentials: ${GOOGLE_FIREBASE_CREDENTIALS}
kira:
  api:
    url: ${KIRA_API_URL}

app:
  jwtSecret: ${SPRING_JWT_KEY}
  jwtExpirationMs: ${SPRING_JWT_EXPIRATION}
